# Generated by Django 5.2.5 on 2025-08-08 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'db_table': 'projetos',
            },
        ),
        migrations.CreateModel(
            name='PontoFuncao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_componente', models.CharField(choices=[('EE', 'Entrada Externa'), ('SE', 'Saída Externa'), ('CE', 'Consulta Externa'), ('ALI', 'Arquivo Lógico Interno'), ('AIE', 'Arquivo de Interface Externa')], max_length=3)),
                ('complexidade', models.CharField(choices=[('LOW', 'Baixa'), ('MEDIUM', 'Média'), ('HIGH', 'Alta')], max_length=10)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apf.projeto')),
            ],
            options={
                'verbose_name': 'Ponto de Função',
                'verbose_name_plural': 'Pontos de Função',
                'db_table': 'pontos_funcao',
            },
        ),
        migrations.CreateModel(
            name='FatorAjuste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processamento_dados', models.IntegerField(default=0)),
                ('desempenho', models.IntegerField(default=0)),
                ('usado_intensivamente', models.IntegerField(default=0)),
                ('taxa_transacao', models.IntegerField(default=0)),
                ('entrada_dados', models.IntegerField(default=0)),
                ('eficiencia_usuario_final', models.IntegerField(default=0)),
                ('atualizacao_online', models.IntegerField(default=0)),
                ('processamento_complexo', models.IntegerField(default=0)),
                ('reutilizacao', models.IntegerField(default=0)),
                ('facil_instalacao', models.IntegerField(default=0)),
                ('facil_operacao', models.IntegerField(default=0)),
                ('multiplos_locais', models.IntegerField(default=0)),
                ('facilitar_mudancas', models.IntegerField(default=0)),
                ('processamento_distribuido', models.IntegerField(default=0)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apf.projeto')),
            ],
            options={
                'verbose_name': 'Fator de Ajuste',
                'verbose_name_plural': 'Fatores de Ajuste',
                'db_table': 'fatores_ajuste',
            },
        ),
    ]
