# Generated by Django 5.2.5 on 2025-08-09 01:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apf', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fatorajuste',
            name='entrada_dados',
        ),
        migrations.RemoveField(
            model_name='fatorajuste',
            name='facil_instalacao',
        ),
        migrations.RemoveField(
            model_name='fatorajuste',
            name='facil_operacao',
        ),
        migrations.RemoveField(
            model_name='fatorajuste',
            name='facilitar_mudancas',
        ),
        migrations.RemoveField(
            model_name='fatorajuste',
            name='processamento_dados',
        ),
        migrations.RemoveField(
            model_name='fatorajuste',
            name='reutilizacao',
        ),
        migrations.RemoveField(
            model_name='fatorajuste',
            name='taxa_transacao',
        ),
        migrations.RemoveField(
            model_name='fatorajuste',
            name='usado_intensivamente',
        ),
        migrations.AddField(
            model_name='fatorajuste',
            name='comunicacao_dados',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='fatorajuste',
            name='configuracao_equipamento',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='fatorajuste',
            name='entrada_dados_online',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='fatorajuste',
            name='facilidade_instalacao',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='fatorajuste',
            name='facilidade_mudanca',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='fatorajuste',
            name='facilidade_operacao',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='fatorajuste',
            name='reusabilidade',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='fatorajuste',
            name='volume_transacoes',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='pontofuncao',
            name='descricao',
            field=models.CharField(blank=True, help_text='Descrição do componente ou referência.', max_length=255),
        ),
        migrations.AlterField(
            model_name='fatorajuste',
            name='atualizacao_online',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='fatorajuste',
            name='desempenho',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='fatorajuste',
            name='eficiencia_usuario_final',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='fatorajuste',
            name='multiplos_locais',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='fatorajuste',
            name='processamento_complexo',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='fatorajuste',
            name='processamento_distribuido',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='fatorajuste',
            name='projeto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fatores_ajuste', to='apf.projeto'),
        ),
    ]
