# Generated by Django 5.2.5 on 2025-08-09 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apf', '0002_remove_fatorajuste_entrada_dados_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Linguagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('produtividade', models.FloatField(help_text='Pontos de Função por dia')),
                ('custo_hora', models.FloatField(help_text='Custo por hora (R$)')),
            ],
            options={
                'verbose_name': 'Linguagem',
                'verbose_name_plural': 'Linguagens',
                'db_table': 'linguagens',
            },
        ),
    ]
